# Generated by Django 6.0.1 on 2026-06-14 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRoleMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('role_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_role_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminUserDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('official_name', models.CharField(max_length=255, null=True)),
                ('official_code', models.CharField(max_length=50, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('official_phone', models.CharField(max_length=15, null=True, unique=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('official_email', models.CharField(max_length=255, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_user_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminDesignationMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=150, unique=True)),
                ('designation_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hierarchy', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.adminrolemaster')),
            ],
            options={
                'db_table': 'admin_designation_master',
                'managed': True,
            },
        ),
    ]
