# Generated by Django 6.0.1 on 2026-06-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuserdetails',
            name='alternate_phone',
        ),
        migrations.RemoveField(
            model_name='adminuserdetails',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='adminuserdetails',
            name='official_code',
        ),
        migrations.RemoveField(
            model_name='adminuserdetails',
            name='official_email',
        ),
        migrations.RemoveField(
            model_name='adminuserdetails',
            name='official_name',
        ),
        migrations.RemoveField(
            model_name='adminuserdetails',
            name='official_phone',
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='designation',
            field=models.ForeignKey(blank=True, db_column='designation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.admindesignationmaster'),
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='mob_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.adminrolemaster'),
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminuserdetails',
            name='user',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.user'),
        ),
    ]
