# Generated by Django 6.0.1 on 2026-07-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('state_name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'state_master',
                'managed': True,
            },
        ),
    ]
