# Generated by Django 6.0.1 on 2026-07-11 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('district_name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='master_management.statemaster')),
            ],
            options={
                'db_table': 'district_master',
                'managed': True,
            },
        ),
    ]
