# Generated by Django 6.0.1 on 2026-07-11 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0002_districtmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('block_name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='master_management.districtmaster')),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='master_management.statemaster')),
            ],
            options={
                'db_table': 'block_master',
                'managed': True,
            },
        ),
    ]
