# Generated by Django 6.0.1 on 2026-07-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0004_rolemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=150, unique=True)),
                ('designation_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, related_name='designations', to='master_management.rolemaster')),
            ],
            options={
                'db_table': 'designation_master',
                'managed': True,
            },
        ),
    ]
