# Generated by Django 6.0.1 on 2026-07-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0005_designationmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conductor_name', models.CharField(max_length=150, unique=True)),
                ('conductor_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conductor_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PoleMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pole_name', models.CharField(max_length=150, unique=True)),
                ('pole_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pole_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransformerMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transformer_name', models.CharField(max_length=150, unique=True)),
                ('transformer_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transformer_master',
                'managed': True,
            },
        ),
    ]
