# Generated by Django 6.0.1 on 2026-08-04 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0006_conductormaster_polemaster_transformermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contractor_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('contractor_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contractor_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VillageMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('village_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('village_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.PROTECT, related_name='villages', to='master_management.blockmaster')),
            ],
            options={
                'db_table': 'village_master',
                'managed': True,
            },
        ),
    ]
