# Generated by Django 6.0.1 on 2026-06-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100, null=True)),
                ('operation', models.CharField(max_length=50, null=True)),
                ('ref_id', models.IntegerField(null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('m_no', models.CharField(blank=True, max_length=150, null=True)),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=500, null=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('active_status', models.SmallIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'login_activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('designation_id', models.IntegerField(blank=True, null=True)),
                ('level', models.SmallIntegerField(blank=True, null=True)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('login_flag', models.BooleanField(default=False, null=True)),
                ('is_password_reset', models.BooleanField(default=False, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
