# Generated by Django 6.0.1 on 2026-08-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainLookup',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_type', models.CharField(db_index=True, max_length=50)),
                ('domain_value', models.CharField(max_length=500)),
                ('domain_code', models.IntegerField(blank=True, null=True)),
                ('domain_desc', models.TextField(blank=True, null=True)),
                ('domain_data_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'domain_lookup',
                'managed': True,
            },
        ),
    ]
