# Generated by Django 6.0.1 on 2026-08-23 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_domainlookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3LikeObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('data', models.BinaryField(blank=True, null=True)),
                ('storage_type', models.CharField(default='database', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 's3_like_object',
                'managed': True,
                'unique_together': {('bucket', 'key')},
            },
        ),
    ]
