# Generated by Django 6.0.1 on 2026-06-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JWTAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='c_m_no',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='c_m_no',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
