# Generated by Django 6.0.1 on 2026-06-14 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contractor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('line_type', models.CharField(choices=[('HT_11KV', '11 KV High Tension Line'), ('HT_33KV', '33 KV High Tension Line'), ('LT_440V', '440 V Low Tension Line')], max_length=50)),
                ('is_synced', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_lines', to='common.user')),
            ],
            options={
                'db_table': 'survey_line',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('POLE', 'Concrete Pole Node'), ('DTR', 'Distribution Transformer Node')], max_length=20)),
                ('sequence_number', models.IntegerField()),
                ('name_label', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_label', models.CharField(blank=True, max_length=150, null=True)),
                ('captured_at', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('survey_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='survey_management.surveyline')),
            ],
            options={
                'db_table': 'survey_node',
                'ordering': ['sequence_number'],
                'managed': True,
            },
        ),
    ]
