# Generated by Django 6.0.1 on 2026-08-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('survey_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErectionExecution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feeder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dtr_code', models.CharField(blank=True, max_length=50, null=True)),
                ('drawing_no', models.CharField(max_length=150)),
                ('state_name', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('block', models.CharField(max_length=150)),
                ('village', models.CharField(max_length=150)),
                ('contractor_name', models.CharField(max_length=255)),
                ('type_of_work', models.CharField(max_length=50)),
                ('lt_starting_point', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erections', to='common.user')),
            ],
            options={
                'db_table': 'erection_execution',
                'managed': True,
            },
        ),
    ]
