# Generated by Django 6.0.1 on 2026-08-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_management', '0002_erectionexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='erectionexecution',
            name='block_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectionexecution',
            name='district_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectionexecution',
            name='state_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectionexecution',
            name='village_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='erectionexecution',
            name='block',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='erectionexecution',
            name='district',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='erectionexecution',
            name='state_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='erectionexecution',
            name='village',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
