# Generated by Django 6.0.1 on 2026-08-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_management', '0003_erectionexecution_block_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erectionexecution',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
