# Generated by Django 6.0.1 on 2026-08-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_management', '0004_erectionexecution_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erectionexecution',
            name='block',
        ),
        migrations.RemoveField(
            model_name='erectionexecution',
            name='contractor_name',
        ),
        migrations.RemoveField(
            model_name='erectionexecution',
            name='district',
        ),
        migrations.RemoveField(
            model_name='erectionexecution',
            name='state_name',
        ),
        migrations.RemoveField(
            model_name='erectionexecution',
            name='village',
        ),
        migrations.AddField(
            model_name='erectionexecution',
            name='contractor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='erectionexecution',
            name='lt_starting_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='erectionexecution',
            name='type_of_work',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
