# Generated by Django 6.0.1 on 2026-08-08 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_management', '0005_remove_erectionexecution_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErectionNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('POLE', 'Concrete Pole Node'), ('DTR', 'Distribution Transformer Node')], max_length=20)),
                ('sequence_number', models.IntegerField()),
                ('name_label', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_label', models.CharField(blank=True, max_length=150, null=True)),
                ('captured_at', models.DateTimeField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('erection_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='survey_management.erectionexecution')),
            ],
            options={
                'db_table': 'erection_node',
                'ordering': ['sequence_number'],
                'managed': True,
            },
        ),
    ]
