# Generated by Django 6.0.1 on 2026-08-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0007_contractormaster_villagemaster'),
        ('survey_management', '0006_erectionnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='erectionnode',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erection_conductor_nodes', to='master_management.conductormaster'),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='dead_end_clamp_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='dtr_capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erection_capacity_nodes', to='master_management.transformermaster'),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='dtr_serial_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='earthing_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='earthing_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='extra_consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='ipc_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='pole_clamp_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='pole_db_quantities',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='pole_db_type_codes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='pole_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='pole_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erection_pole_nodes', to='master_management.polemaster'),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='service_connection_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='stay_set_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='stay_set_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='structure_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='erectionnode',
            name='suspension_clamp_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
