# Generated by Django 6.0.1 on 2026-08-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_management', '0007_erectionnode_conductor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErectionNodeImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_images', to='survey_management.erectionnode')),
            ],
            options={
                'db_table': 'erection_node_image',
                'managed': True,
            },
        ),
    ]
