# Generated by Django 6.0.1 on 2026-10-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0007_contractormaster_villagemaster'),
        ('survey_management', '0008_erectionnodeimage'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='surveyline',
                    name='block_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='surveyline',
                    name='district_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='surveyline',
                    name='feeder_name',
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='surveyline',
                    name='state_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
            ],
            database_operations=[]
        ),
        migrations.CreateModel(
            name='SurveyNodeImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_images', to='survey_management.surveynode')),
            ],
            options={
                'db_table': 'survey_node_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyStructureDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('new_pole_required', models.BooleanField(default=False)),
                ('pole_no', models.CharField(max_length=150)),
                ('pole_qty', models.IntegerField(blank=True, null=True)),
                ('structure_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('existing_conductor', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor_phase_no', models.CharField(blank=True, max_length=50, null=True)),
                ('earthing_type', models.CharField(blank=True, max_length=50, null=True)),
                ('earthing_required', models.CharField(blank=True, max_length=50, null=True)),
                ('existing_stay_set', models.CharField(blank=True, max_length=50, null=True)),
                ('existing_stay_set_qty', models.IntegerField(blank=True, null=True)),
                ('proposed_stay_set', models.CharField(blank=True, max_length=50, null=True)),
                ('new_stay_set_qty', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('existing_dtr_capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_existing_dtr_structures', to='master_management.transformermaster')),
                ('new_dtr_capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_new_dtr_structures', to='master_management.transformermaster')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structure_detail', to='survey_management.surveynode')),
                ('pole_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_structures', to='master_management.polemaster')),
                ('proposed_conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_proposed_conductors', to='master_management.conductormaster')),
                ('survey_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='survey_management.surveyline')),
            ],
            options={
                'db_table': 'survey_structure_detail',
                'managed': True,
            },
        ),
    ]
